### PR TITLE
Fix #235 : try to detect data.mdb for lmdb also

### PR DESCRIPTION
**Pull request by vitan**

### CODE REVIEW

**Comment by vitan** [comment]
@Conan-Kudo  can you detail the broken logic plz? I tested it under BDB, seems it works still

**Comment by Conan-Kudo** [comment]
@vitan Your logic only works as long as a `data.mdb` file exists. If you start with BDB and don't have an LMDB rpmdb on disk, that logic never evaluates.

**Comment by Conan-Kudo** [comment]
This is no longer needed, as it has been fixed differently in ea037722b0f2a1afc8416e08b36fd498a8bb14c4.

This can be closed.

**Comment by Conan-Kudo** [comment]
@mlschroe This can be closed, since LMDB has been removed from RPM entirely.

**Comment by vitan** [comment]
> @mlschroe This can be closed, since LMDB has been removed from RPM entirely.

hi, how are you. where I can get the reason that lmdb removed ?

**Comment by Conan-Kudo** [comment]
The reason is declared in https://github.com/rpm-software-management/rpm/commit/7de982ac0957c42f228b43685d9f486e55eac331

**Comment by mlschroe** [comment]
Closing as we're following rpm upstream in this regard.

**Pull request closed without merging**
