### PR TITLE
Expose pool.set_/get_considered in Python bindings

### PR DESCRIPTION
**Pull request by dparalen**
This patch exposes pool.considered bitmap thru a pair of get/set methods.

Fixes: #258

### CODE REVIEW

**Comment by mlschroe** [comment]
Hmm, I think this is way too complicated for what it does. But I do like the idea of using a "list of set bits". So let's do it like this: We'll add:

```
pool.set_considered_list(list)
list = pool.get_considered_list()
```

That's basically the interface of your helpers. But we do not need a typemap for this, we can simply use the Queue typemap to implement those two functions. (I.e. it will also work for perl/ruby/tcl)

**Comment by dparalen** [comment]
@mlschroe with the update, the interface looks like this in Python:

```
In [1]: import solv

In [2]: p = solv.Pool()

In [3]: s = p.add_repo('r').add_solvable()

In [4]: p.get_considered()
Out[4]: []

In [5]: p.set_considered([0, 0, 1])

In [6]: p.get_considered()[s.id] & 1
Out[6]: 0

In [7]: p.get_considered()[s.id] != 0
Out[7]: True

In [8]: p.get_considered()[s.id] & 7
Out[8]: 4

In [9]: p.set_considered([])

In [10]: p.get_considered()
Out[10]: []
```

**Comment by ignatenkobrain** [comment]
Any reason not to use True/False?

**Comment by dparalen** [comment]
might have to implement a language-specific conversion to the target language array then because `True/False` are objects in e.g Python.

How about exposing some `def set_considered_pythonic()` method that would take care about this and could work with e.g sets instead?

**Comment by ignatenkobrain** [comment]
```c
%typemap(out) bool {
   
    if($1)
        $result = (PyObject *)Py_True;
    else
        $result = (PyObject *)Py_False;
}
```

Won't something like this work?

**Comment by dparalen** [comment]
Actually, never mind me O:-) updated with the additional conversion:

```
In [1]: import solv                                                                                                                                                                                                
                                                                                                                                                                                                                   
In [2]: p = solv.Pool()                                                                                                                                                                                            
                                                                                                                                                                                                                   
In [3]: s = p.add_repo('r').add_solvable()                                                                                                                                                                         
                                                                                                                                                                                                                   
In [4]: p.set_considered([False, 0, True])                                                                                                                                                                         
                                                                                                                                                                                                                   
In [5]: p.get_considered()                                                                                                                                                                                         
Out[5]: [False, False, True, False, False, False, False, False]                                                                                                                                                    
                                                                                                                                                                                                                   
In [6]: p.set_considered([])                                                                                                                                                                                       
                                                                                                                                                                                                                   
In [7]: p.get_considered()                                                                                                                                                                                         
Out[7]: []                                                                                                                                                                                                         
```

**Comment by mlschroe** [comment]
Before we do more comment ping/pong I committed something that can act as a base for further improvements. I didn't support the "reset" operation because I don't like to tie it to the empty list. Maybe we need another method for it.

**Comment by dparalen** [comment]
> Hmm, should have looked at the pull request first. So just rename them ;)

lol :D I absolutely didn't notice the name of the methods you were suggesting before, sorry about that

**Comment by dparalen** [comment]
> Before we do more comment ping/pong I committed something that can act as a base for further improvements. I didn't support the "reset" operation because I don't like to tie it to the empty list. Maybe we need another method for it.

Cool, thanks for the patch! Yeah when it comes to the reset, since empty list has the same semantics as everything considered (or doesn't it?) I thought it was OK to use it as the reset "flag" but I'm cool with any other way.

**Comment by dralley** [comment]
@mlschroe I could be doing something wrong, but I cannot get these methods to work.

If I call ```get_considered_list()``` without first using ```set_considered_list()```, it works.

Screenshot from 2019-06-15 18-59-17

If I call ```set_considered_list([True] * 45)```, (there are 45 solvables in the list), then calling ```get_considered_list()``` afterwards is broken.

Screenshot from 2019-06-15 18-02-10

Am I misusing it?  Or is there a memory bug somewhere?  Depsolving was broken after having set the considered list as described above.

**Comment by mlschroe** [comment]
Commit e33bb18fc9205d79228503e13f7a2b6502dd7675 also adds pool.set_disabled_list() and pool.get_disabled_list().

**Comment by mlschroe** [comment]
Closing. Please reopen if something is still missing.
(I'll also document the calls in the bindings manpage)

**Pull request closed without merging**
