### PR TITLE
build: use GNUInstallDirs

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Closes: #128
Signed-off-by: Igor Gnatenko ignatenko@redhat.com

### CODE REVIEW

**Comment by mlschroe** [comment]
Sorry, we can't require that version of cmake, as it is not available in SLE-11.
But we can use GNUInstallDirs conditionally if you insist on using it.

**Comment by Conan-Kudo** [comment]
@mlschroe That's not true. I'm building software for SUSE Linux Enterprise 11 SP4 using `cmake-2.8.12.1-1.35`. You can totally use it.

**Comment by Conan-Kudo** [comment]
@ignatenkobrain Could you please rebase this against master?

**Comment by ignatenkobrain** [comment]
@Conan-Kudo done.

**Comment by ignatenkobrain** [comment]
@mlschroe ping?

**Comment by Conan-Kudo** [comment]
@mlschroe ping?

**Comment by Conan-Kudo** [comment]
@mlschroe Is there any remaining reason to not merge this in? Switching to GNUInstallDirs allows quite a few projects using libsolv to drop the hacks they're currently using to support all the different variants of filesystem structures (Yocto, Debian, BSD, sysroot-style, etc.). Most, if not all, distributions have CMake adapted at the GNUInstallDirs module level, so projects using it get the adaptations for free.

**Comment by jayvdb** [comment]
@mlschroe ping

**Comment by jayvdb** [comment]
In case it is relevant to this PR being held up, I've created a separate issue to determining and documenting the maximum cmake version permitted : https://github.com/openSUSE/libsolv/issues/217

**Comment by ignatenkobrain** [comment]
I've just rebased this.

**Comment by Conan-Kudo** [comment]
@ignatenkobrain @mlschroe Can we finally pull this in..?

**Comment by Conan-Kudo** [comment]
This is also needed for @wolfv's work on getting this to build properly on Windows as macOS.

**Comment by wolfv** [comment]
yes, this would be great

**Comment by rossburton** [comment]
👍

**Pull request merged**
