### PR TITLE
Fix repodata_set_sourcepkg 'SOLVABLE_SOURCENAME' and 'SOLVABLE_SOURCE…

### PR DESCRIPTION
**Pull request by H0neyBadger**
…EVR'

Remove strncmp check to allow solvable with a different source 'name'

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Can you elaborate more what does not work for you?

**Comment by H0neyBadger** [comment]
Hello, 
I'm running libsolv from fedora and when I check the value of sourceevr and sourcename
its almost always void (or equal to the solvable name).

```
dumpsolv -j /var/cache/dnf/fedora.solv | grep -E 'solvable:(source.*|name)'
...
solvable:name: libsolv
solvable:sourcename: (void)
solvable:sourceevr: (void)
solvable:sourcearch: src
...
``` 
From repodata_set_sourcepkg, there is some checks that verify if the name matches the source file.
but the condition looks reversed and the check by itself verify if the solvable name matches the source name (same verification for evr). 
because most of the time the src name does not match, almost all solvable have a wrong sourcename. 
for example the python3-solv-0.7.7-1.fc30.x86_64.rpm has for source file a difference name libsolv-0.7.7-1.fc30.src.rpm
(I also suspect a side effect with the SELECTION_SOURCE_ONLY flag)

hope this helps

**Comment by ignatenkobrain** [comment]
Note that sourcename is about SOURCERPM, not the RPM filename.

**Comment by H0neyBadger** [comment]
As far as I can see, in the function the solvable name is compared to its sourcepkg name. 
it looks odd to me but I might misunderstood the aim of those fields. 
This issue is not blocking, I just wanted to help a little. 
Feel free to close and/or discard this PR  

Just for comparison. find bellow the result after this change: 
```
solvable:name: libsolv
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
solvable:sourceevr: 0.7.4-2.fc30
solvable:sourcearch: src
solvable:name: libsolv
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
solvable:sourceevr: 0.7.4-2.fc30
solvable:sourcearch: src
solvable:name: libsolv-demo
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
solvable:sourceevr: 0.7.4-2.fc30
solvable:sourcearch: src
solvable:name: libsolv-devel
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
solvable:sourceevr: 0.7.4-2.fc30
solvable:sourcearch: src
solvable:name: libsolv-devel
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
solvable:sourceevr: 0.7.4-2.fc30
solvable:sourcearch: src
solvable:name: libsolv-tools
solvable:evr: 0.7.4-2.fc30
solvable:sourcename: libsolv
```

**Comment by ignatenkobrain** [comment]
that is expected. if the evr / epoch / whatsoever is same, then it is not duplicated.

https://github.com/openSUSE/libsolv/blob/cea2f345d653f161961876a3d5fdeb0b498758ad/src/solvable.c#L394-L424

**Comment by H0neyBadger** [comment]
This is clear now, thank you a lot for those explanations.

**Pull request closed without merging**
