### PR TITLE
Use bash for installing rpms from plain directory

### PR DESCRIPTION
**Pull request by dirkmueller**
Also give an exit code in case globbing failed.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
but this is not equal to the previous code?

**Comment by dirkmueller** [comment]
> but this is not equal to the previous code?

I have tested it for my usecases, and it behaves similarly. what issue do you see ?

**Comment by Conan-Kudo** [comment]
Doesn't this mean that openSUSE has to guarantee bash in minimal environments now?

**Comment by dirkmueller** [comment]
> Doesn't this mean that openSUSE has to guarantee bash in minimal environments now?

we already do have this guarantee.

**Pull request closed without merging**
