### PR TITLE
solv_vercmp_rpm(): implement rpmlib(CaretInVersions) '^' sorting

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Probably I should introduce new flag which will disable this behavior, but @mlschroe will tell me if it's needed ;)

**Comment by Conan-Kudo** [comment]
Looks good to me! :+1:

**Comment by ignatenkobrain** [comment]
replaced Plus with Caret.

**Comment by mlschroe** [comment]
please reopen when rpm upstream supports them.

**Pull request closed without merging**
