### PR TITLE
Added pkg-config file for library.

### PR DESCRIPTION
**Pull request by kirgene**
Signed-off-by: Yevhen Kyriukha <kirgene@gmail.com>

### CODE REVIEW

**Comment by mlschroe** [comment]
Hmm, at least SUSE and Fedora put pkgconfig files for 64bit libraries into /usr/lib64/pkgconfig. Is that different for your distro?

**Comment by kirgene** [comment]
On Debian pkg-config doesn't find pkgconfig files in /usr/lib64/pkgconfig so it should be in /usr/lib/pkgconfig.

**Comment by mlschroe** [comment]
Sigh, why must Debian be different? I'll check how other projects do this.

**Comment by kirgene** [comment]
I checked how curl doing it:
https://github.com/bagder/curl/blob/master/CMakeLists.txt#L1136

**Comment by mlschroe** [comment]
But libcurl can be built both with cmake and configure. The latter installs the file in $(libdir)/pkgconfig, which translates to /usr/lib64/pkgconfig.

Would ${LIB_INSTALL_DIR}/pkgconfig also work for debian? That's probably "/usr/lib/x86_64-linux-gnu/pkgconfig" on your system.

**Comment by kirgene** [comment]
${LIB_INSTALL_DIR}/pkgconfig is /usr/lib64/pkgconfig on my machine. Tested on Ubuntu 14.10 and Debian 7.

**Comment by mlschroe** [comment]
So this is Debian before the multi-arch change? But shouldn't pkg-config also look in that dir? How do you do arch specific pkgconfig files if it only looks in /usr/lib/pkgconfig?

Anyway, I checked a couple of projects and most of them use ${LIB_INSTALL_DIR}/pkgconfig. So I'm tempted to use this and allow to override it with some cmake option.

**Comment by kirgene** [comment]
On Ubuntu x64 I have `/usr/lib` and `/usr/lib32`, also `/usr/lib/i386-linux-gnu` and `/usr/lib/x86_64-linux-gnu` are present. But cmake expands `${LIB_INSTALL_DIR}` to `/usr/lib64`.

**Comment by mlschroe** [comment]
But that's a bug in libsolv's CMakeFile, it should use /usr/lib/i386-linux-gnu on Debian...

(The libsolv package in Jessie calls cmake with ```-DLIB="lib/$(shell dpkg-architecture -qDEB_BUILD_MULTIARCH)"``` as a workaround...)

**Comment by kirgene** [comment]
OK, I'll update pull request to use ${LIB_INSTALL_DIR}/pkgconfig.
But I think that this issue needs to be fixed also. I don't quite understand is this a bug in CMakeFile or in cmake itself?

**Comment by cgwalters** [comment]
pkg-config looks in `/usr/share/pkg-config` for architecture independent packages.  Using `$libdir` in automake parlance for arch-dependent `.pc` files is right.  I believe cmake's `${LIB_INSTALL_DIR}` is equivalent.

**Comment by EricAustinYu** [comment]
I stumbled upon this pull request while searching around as to whether libsolv had a pkg-config file. It seems this request was made a while ago. Is there any news on whether this functionality will be officially added to libsolv?

**Comment by mlschroe** [comment]
Thanks for the reminder. I'll try to add it.

**Pull request merged**
