### PR TITLE
Add support for armv5tl on armsfp arches

### PR DESCRIPTION
**Pull request by Conan-Kudo**
In order to build chroots using Mock, it is necessary to add support for armv5tl.

~~In addition, to be able to build chroots on armhfp hosts for armsfp targets, libsolv needs to allow DNF to solve for armsfp architectures.~~

~~Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1440974~~

Related PR for rpm: https://github.com/rpm-software-management/rpm/pull/199

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@mlschroe Would you prefer for me to split this PR into two so that you can merge the armv5tl patch into libsolv? This is currently being used in Mageia so that armv5tl works properly: http://svnweb.mageia.org/packages/cauldron/libsolv/current/SPECS/libsolv.spec?view=markup

**Comment by mlschroe** [comment]
Yes, that would be nice. Thanks. I'll take the other one if it's in rpm.

**Comment by Conan-Kudo** [comment]
@mlschroe I've purged the second commit from this PR, as rpm didn't take it there either. You can merge this as-is now.

**Comment by Conan-Kudo** [comment]
@mlschroe Is this okay to merge now? The only commit in this PR is the counterpart to the commit in RPM.

**Comment by Conan-Kudo** [comment]
@mlschroe Thanks!

**Pull request merged**
