### PR TITLE
Add support for arch "aarch64:m3ulcb" in poolarch.c

### PR DESCRIPTION
**Pull request by j-mracek**
https://bugzilla.redhat.com/show_bug.cgi?id=1666835

### CODE REVIEW

**Comment by mlschroe** [comment]
libsolv follows rpm for the compatible architecture list. Please push this to rpm first.

**Comment by j-mracek** [comment]
Anyway it looks like that the approach is incorrect according to reporter of the original issue.

**Comment by claneys** [comment]
A bit yes, the solution would be to have this mapping someway, somewhere overridable by a file/env var, like RPM does with its 'rpmrc' file or DNF with its '/etc/dnf/vars/arch' file. The solution would be to let the user configure its system instead of adding any weird arch upstream which is definitely not a solution, I agreed.

Does libsolv could rely on the rpmrc file by example to get its arch mapping ?

**Comment by mlschroe** [comment]
libsolv already supports custom arch policies, you can use pool_setarchpolicy() instead of pool_setarch().

**Comment by j-mracek** [comment]
@mlschroe Thank you for perfect hint. We will think how to implement it in libdnf

**Pull request closed without merging**
