### PR TITLE
bindings: use $self for Selection.clone()

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Doesn't this break API incompatibly?

**Comment by ignatenkobrain** [comment]
@Conan-Kudo yes, except that I wonder if anyone used this API because it's so wrong... `sel.clone(sel)`

**Comment by mlschroe** [comment]
Hmm, yes. Seems like a bad copy/n/paste from my side. It's also not documented. I think it got stuck in mid-implementation. ;)

**Comment by ignatenkobrain** [comment]
alright, I will add documentation.

**Comment by mlschroe** [comment]
You're supposed to patch the .txt file, not the generated .3 file...

**Pull request merged**
