### PR TITLE
Introduced new SOLVABLE_USERINSTALLED attribute to mark user-installed p...

### PR DESCRIPTION
**Pull request by kirgene**
...ackages during cleandeps process.

### CODE REVIEW

**Comment by mlschroe** [comment]
But... but... is there really a "auto-installed" line in the dpkg status file? I thought they live only in /var/lib/apt/extended_states or maybe /var/lib/aptitude/pkgstates.

**Comment by kirgene** [comment]
Ah, I forgot to mention that there are some dpkg compatible package managers like opkg (used in embedded systems). These package managers store all status info in status file.

**Comment by ignatenkobrain** [comment]
ping @kirgene

**Comment by ignatenkobrain** [comment]
Seems nobody is interested in this. Please open a new PR in case this is still relevant.

**Pull request closed without merging**
