### PR TITLE
Feature depriorization first

### LINKED ISSUE #394: [conda] track_feature count depriorization should have higher priority than maximizing versions
This is the behavior of conda, but libsolv appears to priorize maximizing versions.

(The track-feature minimization thing is quite radical in terms of excluding packages).

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #394.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cc @wolfv

**Comment by SylvainCorlay** [comment]
This is working as expected in our downstream project.

**Comment by SylvainCorlay** [comment]
Ping @mlschroe! Let me know if anything else is needed on my side.

This is a straightforward fix, and it is already integrated as a patch in the libsolv conda package!

**Comment by wolfv** [comment]
it would be quite cool to have a release with this :)

**Pull request merged**
