### PR TITLE
Fix regex bug on windows

### PR DESCRIPTION
**Pull request by tl-hbk**
Fixes this issue https://github.com/openSUSE/libsolv/issues/435 

Details in this thread https://github.com/mamba-org/mamba/issues/725#issuecomment-791353298

### CODE REVIEW

**Comment by mlschroe** [comment]
What"s wrong with ssize_t?

**Comment by tl-hbk** [comment]
@mlschroe it would fail to build when I tried to use `ssize_t` with msvc

**Comment by mlschroe** [comment]
Even if you do a `#include <sys/types.h>`?

**Comment by tl-hbk** [comment]
Yes

**Comment by tl-hbk** [comment]
@mlschroe would you prefer `SSIZE_T` be used in this case?

**Comment by mlschroe** [comment]
Yes. I think `long` is just 32bit and thus wrong for _WIN64. (I'm not sure about this, that's just what searching around the internet came up with.)

**Comment by tl-hbk** [comment]
@mlschroe change made

**Comment by mlschroe** [comment]
Thanks!

**Comment by tl-hbk** [comment]
With your comment mentioning `long` being 32bit for windows, I noticed that `long` is used here 
https://github.com/openSUSE/libsolv/blob/master/win32/tre.h#L79-L82 and all the calls to `ALIGN` as well
https://github.com/openSUSE/libsolv/blob/master/win32/regexec.c#L245-L254

I'm assuming this needs to be fixed?

**Pull request merged**
